// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEFEkICGF3q4csy_8e2FL5HG2LMSguMKc',
    appId: '1:473749044255:web:37eda386f67ecd805f692a',
    messagingSenderId: '473749044255',
    projectId: 'sushisishu-d4673',
    authDomain: 'sushisishu-d4673.firebaseapp.com',
    storageBucket: 'sushisishu-d4673.firebasestorage.app',
    measurementId: 'G-874KD6YYQ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADtXjV1qiAF2LLGlOU6ck3jGRRexe1JFw',
    appId: '1:473749044255:android:1bc1ec4022b23bef5f692a',
    messagingSenderId: '473749044255',
    projectId: 'sushisishu-d4673',
    storageBucket: 'sushisishu-d4673.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxy1xR-8OGp2XUPAWUI8fxzug-E5JWhvs',
    appId: '1:473749044255:ios:0923ba9204265fd45f692a',
    messagingSenderId: '473749044255',
    projectId: 'sushisishu-d4673',
    storageBucket: 'sushisishu-d4673.firebasestorage.app',
    iosBundleId: 'com.example.sushiRestaurant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEFEkICGF3q4csy_8e2FL5HG2LMSguMKc',
    appId: '1:473749044255:web:0b3730f109504eac5f692a',
    messagingSenderId: '473749044255',
    projectId: 'sushisishu-d4673',
    authDomain: 'sushisishu-d4673.firebaseapp.com',
    storageBucket: 'sushisishu-d4673.firebasestorage.app',
    measurementId: 'G-JDF0727R6Y',
  );
}
